@startuml
skinparam actorStyle awesome
left to right direction

skinparam usecase {
    BackgroundColor #E8F1FF
    BorderColor #2F5EA8
    ArrowColor #2F5EA8
    ActorBorderColor #1F3F73
    ActorBackgroundColor #EEF5FF
}

actor "Presidente" as Presidente
actor "Residente" as Residente
actor "Sistema (Automático)" as Sistema

note as N1
Administrador puede realizar
todos los casos de uso
del módulo.
end note

rectangle "Módulo de Pagos y Finanzas" {

    ' CASOS DE USO DEL PRESIDENTE
    usecase "registrarDeuda" as RegistrarDeuda
    usecase "registrarPagoEfectivoTransferenciaResidente" as RegistrarPagoEfectivoTransferencia
    usecase "modificarFechaMaximaPagoDeUnaDeuda" as ModificarFechaMaximaPago
    usecase "definirValorMensualAlicuotas" as DefinirValorMensualAlicuotas
    usecase "generarReportePagosRealizados" as GenerarReportePagos
    usecase "registrarEntidadBancaria" as RegistrarEntidadBancaria
    usecase "eliminarDeuda" as EliminarDeuda
    usecase "generarReporteRendicionCuentas" as GenerarReporteRendicionCuentas
    usecase "registrarPagosCondominio" as RegistrarPagoExterno
    usecase "generarReporteGastos" as GenerarReporteGastos

    ' CASOS DE USO DEL RESIDENTE
    usecase "pagarDeuda" as pagarDeuda
    usecase "solicitarPagoCuotas" as SolicitarPagoCuotas
    usecase "generarCertificadoNoDeudor" as GenerarCertificadoNoDeudor
    

    ' CASOS DE USO COMPARTIDOS
    usecase "consultarDeuda" as ConsultarDeuda
    usecase "consultarPagosEfectuados" as ConsultarPagosEfectuados
    usecase "consultarReporteRendicionCuentas" as ConsultarReporteRendicionCuentas

    ' CASOS DE USO DEL SISTEMA
    usecase "registrarDeudaAlicuotaMensual" as RegistrarDeudaMensual
    usecase "enviarRecordatorioDeudaPendiente" as EnviarRecordatorioDeuda
    usecase "registrarMoraDeDeuda" as RegistrarMoraDeDeuda
    usecase "notificarReporteRendicionCuentas" as NotificarReporteRendicionCuentas
}

' ------------------------
' Relaciones del Residente
' ------------------------
Residente --> pagarDeuda
Residente --> ConsultarDeuda
Residente --> ConsultarPagosEfectuados
Residente --> SolicitarPagoCuotas
Residente --> GenerarCertificadoNoDeudor
Residente --> ConsultarReporteRendicionCuentas

' ------------------------
' Relaciones del Presidente
' ------------------------
Presidente --> RegistrarDeuda
Presidente --> RegistrarPagoEfectivoTransferencia
Presidente --> ConsultarDeuda
Presidente --> ModificarFechaMaximaPago
Presidente --> DefinirValorMensualAlicuotas
Presidente --> GenerarReportePagos
Presidente --> RegistrarEntidadBancaria
Presidente --> ConsultarPagosEfectuados
Presidente --> EliminarDeuda
Presidente --> GenerarReporteRendicionCuentas
Presidente --> RegistrarPagoExterno
Presidente --> GenerarReporteGastos
Presidente --> ConsultarReporteRendicionCuentas

' ------------------------
' Relaciones del Sistema
' ------------------------
Sistema --> EnviarRecordatorioDeuda
Sistema --> RegistrarDeudaMensual
Sistema --> RegistrarMoraDeDeuda
Sistema --> NotificarReporteRendicionCuentas




@enduml