package fis.dsw.sgc.comunicacion.model;
public enum TipoComunicacion {
    MENSAJE_RESIDENTES, COMUNICADO_TRABAJADORES, MENSAJE_GLOBAL, ANUNCIO_GENERAL,
    MENSAJE_URGENTE, ALERTA_EMERGENCIA, BOLETIN_INFORMATIVO
}
