@startuml C4_Context_Diagram

!include ../../libs/c4/C4_Context.puml

title Sistema de Gestión de Condominio - Context Diagram

skinparam wrapWidth 100

skinparam nodesep 100
skinparam ranksep 40

Person(admin, "Administrador", "Gestiona usuarios,\ninmuebles y comunicaciones.")
Person(president, "Presidente", "Supervisa la administración\ndel condominio.")
Person(resident, "Residente", "Realiza pagos, reservas\ny recibe notificaciones.")
Person(owner, "Propietario", "Administra la información\nde sus inmuebles.")
Person(security, "Empleado", "Cualquier empleado de la organización con funciones en particular.")

System(condominio_sys, "Sistema de Gestión de Condominio", "Gestiona usuarios, pagos,\ninmuebles, reservas, visitas y comunicaciones.")
System_Ext(payment_sys, "Sistema de Gestión de Pagos", "Procesa pagos con tarjeta y transferencias.")
System_Ext(gmail_sys, "Gmail", "Servicio de correo externo para envío del código de recuperación de contraseña.")

Rel(admin, condominio_sys, "Administra el sistema")
Rel(president, condominio_sys, "Consulta información\ny recibe reportes")
Rel(resident, condominio_sys, "Gestiona pagos,\nreservas y perfil")
Rel(owner, condominio_sys, "Gestiona propiedades")
Rel(security, condominio_sys, "Registra visitas\ny accesos\nRecibe notificaciones")

Rel(condominio_sys, payment_sys, "Procesa y confirma pagos")
Rel(condominio_sys, gmail_sys, "Envía código de recuperación\nde contraseña", "SMTP")

@enduml



en casos de uso, eliminar *eliminarFormaDePagoRecurrente*,
registrarPago es general, se utiliza para alicuotas, multas y reservas