@startuml GRB_Gestion_Usuarios_Administradores

title Módulo GRB - Gestión de Usuarios y Administradores

'Configura de estilo
left to right direction
skinparam packageStyle rectangle

' Definición de actores, casos de uso y relaciones
rectangle {

    'Actores
    actor "Usuario" as USR
    actor "Administrador" as ADM

    'Casos de uso
    usecase "registrarCuenta" as CU1 
    usecase "actualizarInformacionDeCuenta" as CU2 
    usecase "desactivarCuenta" as CU3

    usecase "asignarRolAUsuario" as CU4 
    usecase "definirPermisosDeRol" as CU5

    usecase "iniciarSesion" as CU6 

    usecase "actualizarPerfil" as CU7
    usecase "recuperarContrasena" as CU8 

    usecase "enviarTokenDeRestablecimiento" as CU9 

    ' Relación include
    CU8 .> CU9 : <<include>>

}

' Relaciones Usuario
USR --> CU6
USR --> CU8
USR --> CU7

' Relaciones Administrador
ADM --> CU6
ADM --> CU1
ADM --> CU2
ADM --> CU3
ADM --> CU4
ADM --> CU5

@enduml
