@startuml GRF_Modulo_Comunicacion

title Módulo GRF - Comunicación

skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle

skinparam usecase {
    BackgroundColor #E8F1FF
    BorderColor #2F5EA8
    ArrowColor #2F5EA8
    ActorBorderColor #1F3F73
    ActorBackgroundColor #EEF5FF
}

actor "Administrador" as ADM
actor "Residente" as RES
actor "Trabajador" as TRA
actor "Sistema (Automático)" as SIS

rectangle "Módulo GRF - Comunicación" {

    usecase "enviarMensajeAResidentes" as CU1
    usecase "enviarComunicadoATrabajadores" as CU2
    usecase "enviarMensajeGlobal" as CU3
    usecase "crearAnuncioGeneral" as CU4
    usecase "modificarAnuncioGeneral" as CU5
    usecase "eliminarAnuncioGeneral" as CU6
    usecase "crearReporteDeComunicacion" as CU7
    usecase "consultarHistorialDeMensajes" as CU8
    usecase "registrarHistorialDeComunicaciones" as CU9
    usecase "notificarMensajeRecibido" as CU10
}

ADM --> CU1
ADM --> CU2
ADM --> CU3
ADM --> CU4
ADM --> CU5
ADM --> CU6
ADM --> CU7
ADM --> CU8

RES --> CU8
TRA --> CU8

SIS --> CU9
SIS --> CU10

@enduml